from typing import List
from pydantic import Json
from datetime import datetime

job_posts: List[Json] = [
    {
        "job": "Machine Learning engineer",
        "description": "We are looking for enthusiastic ML engineer who are dedicated to the job and are willing to work as a team.",
        "job_location": "Kathmandu",
        "job_level": "Senior",
        "job_type": "Permanent",
        "job_responsibilities": ["Must be able to create ml models", "Should be able to data prepration", "Should be able to make deep learning systems", "Researching and implementing ML algorithms and tools", "Picking appropriate data representation methods."],
        "skills": ["ml", "dl", "ai", "fastapi"],
        "minimum_years_of_experience": 3,
        "education_required": "Bachlors",
        "no_of_vacancy": 2,
        "work_hours": "10 am to 5 pm",
        "min_salary": 40000,
        "max_salary": 100000,
        "job_benefits": ["Health insurance.", "Handsome bonus", "Flexible work Schedule", "Paid time off"],
        "job_start_date": datetime(2022, 12, 15, 14, 00, 00),
        "remote_onsite": "onsite",
        "status_of_jobs": "published",
        "posted_date": datetime.utcnow(),
        "deadline": datetime(2022, 12, 3, 14, 00, 00),
        "employer_id": 1,
    },
    {
        "job": "Web developer",
        "description": "Our Company is dedicated to provide a good service to our customers and we are looking for full stack intern.",
        "job_location": "Banepa",
        "job_level": "Internship",
        "job_type": "Internship",
        "job_responsibilities": ["Api creation", "UI development", "Database Management", "Website and software application designing, building, or maintaining"],
        "skills": ["js", "html", "react", "flutter"],
        "minimum_years_of_experience": 0,
        "education_required": "Bachlors",
        "no_of_vacancy": 5,
        "work_hours": "10 am to 5 pm",
        "min_salary": 30000,
        "max_salary": 40000,
        "job_benefits": ["Transportation Expense", "Lunch will be provided", "Paid time off 7 days a year", "Dental Insurance"],
        "job_start_date": datetime(2023, 1, 15, 14, 00, 00),
        "remote_onsite": "remote",
        "status_of_jobs": "published",
        "posted_date": datetime.utcnow(),
        "deadline": datetime(2023, 1, 1, 14, 00, 00),
        "employer_id": 2,
    }
]
